kind: pipeline
name: default
type: kubernetes
trigger:
  branch:
    - master
  event:
    include:
      - push
steps:
  - name: github-packages-auth
    image: robertstettner/drone-npm-auth
    settings:
      username:
        from_secret: GITHUB_PACKAGES_USERNAME
      password:
        from_secret: GITHUB_PACKAGES_PASSWORD
      email:
        from_secret: GITHUB_PACKAGES_EMAIL
      registry:
        from_secret: GITHUB_PACKAGES_REGISTRY
      scope: '@vase'

  - name: publish
    image: node:12-alpine
    environment:
      npm_config_unsafe_perm: 'true'
    commands:
      - yarn install
      - yarn lerna publish from-package --yes

---
kind: secret
name: GITHUB_PACKAGES_USERNAME
get:
  path: secret/data/infra_secrets/global_secrets
  name: GITHUB_PACKAGES_USERNAME

---
kind: secret
name: GITHUB_PACKAGES_PASSWORD
get:
  path: secret/data/infra_secrets/global_secrets
  name: GITHUB_PACKAGES_PASSWORD

---
kind: secret
name: GITHUB_PACKAGES_EMAIL
get:
  path: secret/data/infra_secrets/global_secrets
  name: GITHUB_PACKAGES_EMAIL

---
kind: secret
name: GITHUB_PACKAGES_REGISTRY
get:
  path: secret/data/infra_secrets/global_secrets
  name: GITHUB_PACKAGES_REGISTRY

